#!/usr/bin/env python3
"""ui-craft direction — the six-line brief as an executable, persisted artifact.

  python3 direction.py init      [--out docs/design/brief.json]        a template to fill in
  python3 direction.py from-css  src/index.css [--out docs/design/brief.json]
                                                                       seed a brief from a project's existing tokens
  python3 direction.py check     docs/design/brief.json [--fix]        every colour role measured, light and dark;
                                                                       --fix nudges failing text/accent/boundary
                                                                       tokens in OKLCH lightness until they pass
  python3 direction.py write     docs/design/brief.json [--css src/index.css] [--doc docs/design/DIRECTION.md] [--force]
                                                                       emit the @theme block (+ dark override) into the
                                                                       CSS between markers, and the human-readable
                                                                       DIRECTION.md with the measured ratios

Roles (brief.json → "roles"):
  surface   backgrounds text sits on                     no rule of their own
  text      body / muted / headings                      ≥ 4.5:1 on every surface
  accent    {"brand": "brand-fg"} — the accent as text on every surface ≥ 4.5:1,
            and its foreground on it ≥ 4.5:1 (a filled button)
  boundary  control borders, focus rings                  ≥ 3:1 on every surface
  hairline  decorative dividers                           exempt

The next session reads DIRECTION.md before touching the project (inspect.py finds it), so
decisions persist instead of being re-rolled. Standard library only.
"""
import json
import math
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from contrast import parse_color, ratio, strip_comments, tokens_from_css  # noqa: E402

TEXT_MIN, ACCENT_MIN, BOUNDARY_MIN = 4.5, 4.5, 3.0
MARK_START, MARK_END = "/* ui-craft:tokens — generated by direction.py; edit the brief, not this block */", "/* /ui-craft:tokens */"

TEMPLATE = {
    "name": "Project",
    "audience": "who, and what state they are in when they see this",
    "feel": ["adjective", "adjective", "one non-obvious adjective"],
    "distinctive": "the ONE deliberate choice (type, colour, layout, or restraint) that makes this not-generic",
    "density": "standard",
    "type": {"display": "Fraunces", "body": "IBM Plex Sans", "mono": "IBM Plex Mono", "why": "why this pair"},
    "radius": "6px",
    "roles": {
        "surface": ["surface", "panel"],
        "text": ["ink", "muted"],
        "accent": {"brand": "brand-fg"},
        "boundary": ["line-strong"],
        "hairline": ["line"],
    },
    "light": {"surface": "#fbf8f3", "panel": "#ffffff", "ink": "#2a2320", "muted": "#6b615b",
              "line": "#e5ddd3", "line-strong": "#948980", "brand": "#b5451b", "brand-fg": "#ffffff"},
    "dark": {"surface": "#17120f", "panel": "#221c18", "ink": "#f2ebe3", "muted": "#aca196",
             "line": "#3f362f", "line-strong": "#7d7268", "brand": "#e8744a", "brand-fg": "#1a1210"},
    "pages": [],
}


# ------------------------------------------------------------ colour maths
def srgb_to_oklch(rgb):
    r, g, b = (max(0.0, min(255.0, c)) / 255 for c in rgb[:3])
    def lin(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = lin(r), lin(g), lin(b)
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l, m, s = (x ** (1 / 3) for x in (l, m, s))
    L = 0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s
    a = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s
    bb = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s
    C = math.hypot(a, bb)
    H = math.degrees(math.atan2(bb, a)) % 360
    return L, C, H


def oklch_to_rgb_clamped(L, C, H):
    """OKLCH → sRGB, reducing chroma until the colour fits the gamut."""
    a = C * math.cos(math.radians(H)); b = C * math.sin(math.radians(H))
    for _ in range(40):
        l_ = L + 0.3963377774 * a + 0.2158037573 * b
        m_ = L - 0.1055613458 * a - 0.0638541728 * b
        s_ = L - 0.0894841775 * a - 1.2914855480 * b
        l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
        r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
        g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
        bl = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
        if all(-0.001 <= c <= 1.001 for c in (r, g, bl)):
            break
        a *= 0.92; b *= 0.92
    def gam(c):
        c = max(0.0, min(1.0, c))
        return 255 * (1.055 * c ** (1 / 2.4) - 0.055 if c > 0.0031308 else 12.92 * c)
    return (gam(r), gam(g), gam(bl), 1.0)


def hexs(rgb):
    return "#%02x%02x%02x" % tuple(int(round(c)) for c in rgb[:3])


# ------------------------------------------------------------------- brief
def load_brief(path: Path) -> dict:
    b = json.loads(path.read_text(encoding="utf-8"))
    for key in ("roles", "light"):
        if key not in b:
            raise SystemExit(f"brief is missing '{key}'")
    b.setdefault("dark", {})
    return b


def rules(brief: dict):
    """Yield (scheme, token, against, minimum, kind) for every pair the roles imply."""
    roles = brief["roles"]
    surfaces = roles.get("surface", [])
    for scheme in ("light", "dark"):
        pal = brief.get(scheme) or {}
        if not pal:
            continue
        for t in roles.get("text", []):
            for s in surfaces:
                yield scheme, t, s, TEXT_MIN, "text"
        for accent, fg in (roles.get("accent") or {}).items():
            for s in surfaces:
                yield scheme, accent, s, ACCENT_MIN, "accent-as-text"
            if fg:
                yield scheme, fg, accent, ACCENT_MIN, "fg-on-accent"
        for t in roles.get("boundary", []):
            for s in surfaces:
                yield scheme, t, s, BOUNDARY_MIN, "boundary"


def measure(brief: dict):
    rows, missing = [], []
    for scheme, tok, against, minimum, kind in rules(brief):
        pal = brief[scheme]
        if tok not in pal or against not in pal:
            missing.append(f"{scheme}: '{tok}' or '{against}' has no value")
            continue
        fg, bg = parse_color(pal[tok]), parse_color(pal[against])
        if not fg or not bg:
            missing.append(f"{scheme}: cannot parse '{pal.get(tok)}' / '{pal.get(against)}'")
            continue
        r = ratio(fg, bg)
        rows.append({"scheme": scheme, "token": tok, "against": against, "ratio": round(r, 2), "min": minimum, "kind": kind, "ok": r >= minimum})
    return rows, missing


def fix(brief: dict, rows):
    """Nudge failing tokens (never surfaces) in OKLCH lightness until every rule they are in passes."""
    changes = []
    failing = [r for r in rows if not r["ok"]]
    for scheme in ("light", "dark"):
        pal = brief.get(scheme) or {}
        toks = sorted({r["token"] for r in failing if r["scheme"] == scheme})
        for tok in toks:
            own = [r for r in rules(brief) if r[0] == scheme and r[1] == tok]
            if not own:
                continue
            rgb = parse_color(pal[tok])
            L, C, H = srgb_to_oklch(rgb)
            # move away from the mean lightness of what it sits on
            againsts = [parse_color(pal[r[2]]) for r in own if r[2] in pal]
            mean_L = sum(srgb_to_oklch(a)[0] for a in againsts) / max(1, len(againsts))
            step = -0.01 if L >= mean_L and mean_L > 0.5 else (0.01 if L <= mean_L else -0.01)
            if mean_L > 0.5:
                step = -0.01
            else:
                step = 0.01
            before = pal[tok]
            for _ in range(80):
                ok = all(ratio(parse_color(pal[tok]), parse_color(pal[r[2]])) >= r[3] for r in own if r[2] in pal)
                if ok:
                    break
                L = max(0.0, min(1.0, L + step))
                pal[tok] = hexs(oklch_to_rgb_clamped(L, C, H))
                if L in (0.0, 1.0):
                    break
            if pal[tok] != before:
                changes.append((scheme, tok, before, pal[tok]))
    return changes


# ----------------------------------------------------------------- outputs
def css_block(brief: dict) -> str:
    light, dark = brief["light"], brief.get("dark") or {}
    lines = [MARK_START, "@theme {"]
    for k, v in light.items():
        lines.append(f"  --color-{k}: {v};")
    t = brief.get("type") or {}
    if t.get("display"):
        lines.append(f'  --font-display: "{t["display"]}", Georgia, serif;')
    if t.get("body"):
        lines.append(f'  --font-body: "{t["body"]}", system-ui, sans-serif;')
    if t.get("mono"):
        lines.append(f'  --font-mono: "{t["mono"]}", ui-monospace, monospace;')
    if brief.get("radius"):
        lines.append(f"  --radius-md: {brief['radius']};")
    lines.append("}")
    if dark:
        lines.append("@media (prefers-color-scheme: dark) {")
        lines.append("  :root {")
        for k, v in dark.items():
            lines.append(f"    --color-{k}: {v};")
        lines.append("  }")
        lines.append("}")
    lines.append(MARK_END)
    return "\n".join(lines) + "\n"


def write_css(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8") if path.exists() else '@import "tailwindcss";\n'
    if MARK_START in text and MARK_END in text:
        s, e = text.index(MARK_START), text.index(MARK_END) + len(MARK_END)
        text = text[:s] + block.rstrip("\n") + text[e:]
        how = "replaced the ui-craft block"
    else:
        m = re.search(r"@theme\b[^{]*\{", text)
        if m:  # replace the project's first @theme block so tokens are not declared twice
            depth, i = 0, m.end() - 1
            for j in range(i, len(text)):
                if text[j] == "{":
                    depth += 1
                elif text[j] == "}":
                    depth -= 1
                    if depth == 0:
                        text = text[:m.start()] + block.rstrip("\n") + text[j + 1:]
                        break
            how = "replaced the existing @theme block"
        else:
            imp = re.search(r"@import\s+[\"']tailwindcss[\"'];?\n", text)
            at = imp.end() if imp else 0
            text = text[:at] + "\n" + block + text[at:]
            how = "inserted after @import \"tailwindcss\"" if imp else "inserted at the top"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return how


def doc_text(brief: dict, rows, source: str) -> str:
    feel = ", ".join(brief.get("feel", []))
    t = brief.get("type") or {}
    out = [f"# {brief.get('name', 'Project')} — design direction", "",
           f"_Generated by ui-craft `direction.py` from `{source}` on {datetime.now(timezone.utc).strftime('%Y-%m-%d')}. Edit the brief and re-run `direction.py write`; do not edit the token block in the CSS by hand._", "",
           "## Brief", "",
           f"- **Audience:** {brief.get('audience', '')}",
           f"- **Feel:** {feel}",
           f"- **Distinctive:** {brief.get('distinctive', '')}",
           f"- **Palette roles:** surfaces {', '.join(brief['roles'].get('surface', []))} · text {', '.join(brief['roles'].get('text', []))} · accent {', '.join((brief['roles'].get('accent') or {}).keys())} · boundaries {', '.join(brief['roles'].get('boundary', []))} · hairlines {', '.join(brief['roles'].get('hairline', []))}",
           f"- **Type:** display {t.get('display', '—')} · body {t.get('body', '—')}" + (f" · mono {t['mono']}" if t.get("mono") else "") + (f" — {t['why']}" if t.get("why") else ""),
           f"- **Density:** {brief.get('density', 'standard')}" + (f" · radius {brief['radius']}" if brief.get("radius") else ""),
           "", "## Tokens", "", "| token | light | dark |", "|---|---|---|"]
    dark = brief.get("dark") or {}
    for k, v in brief["light"].items():
        out.append(f"| `{k}` | `{v}` | `{dark.get(k, '—')}` |")
    out += ["", "## Measured contrast", "",
            "Text and accent roles need 4.5:1 on every surface, boundaries 3:1. Numbers from `direction.py check`; the render loop re-measures them on the page.", "",
            "| pair | light | dark |", "|---|---|---|"]
    pairs = {}
    for r in rows:
        pairs.setdefault((r["token"], r["against"], r["min"]), {})[r["scheme"]] = r
    for (tok, against, minimum), by in pairs.items():
        cell = lambda s: (f"{by[s]['ratio']}:1 {'✓' if by[s]['ok'] else '✗'}" if s in by else "—")
        out.append(f"| `{tok}` on `{against}` (≥ {minimum}) | {cell('light')} | {cell('dark')} |")
    out += ["", "## Pages", ""]
    pages = brief.get("pages") or []
    out += [f"- `{p.get('route', '?')}` — {p.get('note', '')}" for p in pages] or ["- (none recorded yet — add `{\"route\": \"/pricing\", \"note\": \"…\"}` to `pages` in the brief when a page is built)"]
    out += ["", "## Rules of the house", "",
            "- One accent, one job (actions). Neutrals do the structural work.",
            "- Reuse these tokens; add a token to the brief before inventing a colour in a component.",
            "- Every new page: render with `render.mjs`, paste the Verified block, add the page above.", ""]
    return "\n".join(out)


def brief_from_css(css_path: Path) -> dict:
    light, dark = tokens_from_css(css_path.read_text(encoding="utf-8"))
    strip = lambda k: k[8:] if k.startswith("--color-") else k.lstrip("-")
    L = {strip(k): v for k, v in light.items() if k.startswith("--color-")}
    D = {strip(k): v for k, v in dark.items() if k.startswith("--color-")}
    names = list(L)
    pick = lambda *pats: [n for n in names if any(re.search(p, n) for p in pats)]
    surfaces = pick(r"^(surface|bg|background|panel|card|paper|sheet|canvas)$", r"^(surface|bg)-") or names[:1]
    text = pick(r"^(ink|text|fg|foreground|muted|secondary|subtle)$", r"^(text|ink)-")
    accents = pick(r"^(brand|primary|accent)$")
    accent = {}
    for a in accents:
        fg = next((n for n in names if n in (f"{a}-fg", f"{a}-foreground", "on-" + a)), None)
        accent[a] = fg
    boundary = pick(r"^(line-strong|border-strong|ring|outline)$")
    hairline = pick(r"^(line|border|divider|rule)$")
    css = strip_comments(css_path.read_text(encoding="utf-8"))
    fonts = dict(re.findall(r"--font-([\w-]+)\s*:\s*([^;]+);", css))
    first = lambda v: v.split(",")[0].strip().strip("'\"") if v else None
    radius = re.search(r"--radius-md\s*:\s*([^;]+);", css)
    return {
        "name": css_path.resolve().parent.parent.name,
        "audience": "", "feel": [], "distinctive": "", "density": "standard",
        "type": {"display": first(fonts.get("display")), "body": first(fonts.get("body") or fonts.get("sans")), "mono": first(fonts.get("mono")), "why": ""},
        "radius": radius.group(1).strip() if radius else None,
        "roles": {"surface": surfaces, "text": text, "accent": accent, "boundary": boundary, "hairline": hairline},
        "light": L, "dark": D, "pages": [],
    }


# -------------------------------------------------------------------- main
def main() -> int:
    a = sys.argv[1:]
    if not a or a[0] in ("-h", "--help"):
        print(__doc__); return 0
    cmd = a[0]
    opt = lambda flag, default=None: a[a.index(flag) + 1] if flag in a else default

    if cmd == "init":
        out = Path(opt("--out", "docs/design/brief.json"))
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(TEMPLATE, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"template written → {out}. Fill it in, then: direction.py check {out} --fix && direction.py write {out}")
        return 0

    if cmd == "from-css":
        css = Path(a[1]); out = Path(opt("--out", "docs/design/brief.json"))
        brief = brief_from_css(css)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(brief, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        rows, missing = measure(brief)
        bad = [r for r in rows if not r["ok"]]
        print(f"brief seeded from {css} → {out}: {len(brief['light'])} light tokens, {len(brief['dark'])} dark; roles guessed from names — check them.")
        print(f"measured {len(rows)} pairs, {len(bad)} below their minimum" + (f": " + ", ".join(f"{r['scheme']} {r['token']}/{r['against']} {r['ratio']}:1" for r in bad[:6]) if bad else ""))
        return 0

    if cmd in ("check", "write"):
        bp = Path(a[1]); brief = load_brief(bp)
        rows, missing = measure(brief)
        for m in missing:
            print(f"WARN  {m}")
        bad = [r for r in rows if not r["ok"]]
        if bad and "--fix" in a:
            changes = fix(brief, rows)
            for scheme, tok, before, after in changes:
                print(f"fixed {scheme} {tok}: {before} → {after}")
            bp.write_text(json.dumps(brief, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            rows, missing = measure(brief)
            bad = [r for r in rows if not r["ok"]]
        for r in rows:
            print(f"{'ok  ' if r['ok'] else 'FAIL'}  {r['scheme']:5} {r['token']} on {r['against']}: {r['ratio']}:1 (need {r['min']}, {r['kind']})")
        print(f"Direction: {len(rows)} pairs measured across {'light + dark' if brief.get('dark') else 'light'}, {len(bad)} below minimum")
        if cmd == "check":
            return 1 if bad else 0
        if bad and "--force" not in a:
            print("not written: fix the pairs above (or --fix, or --force)"); return 1
        css = opt("--css"); doc = Path(opt("--doc", str(bp.parent / "DIRECTION.md")))
        if css:
            how = write_css(Path(css), css_block(brief))
            print(f"tokens → {css} ({how})")
        else:
            print(css_block(brief))
        doc.parent.mkdir(parents=True, exist_ok=True)
        doc.write_text(doc_text(brief, rows, bp.name), encoding="utf-8")
        print(f"direction → {doc}")
        return 0

    print(f"unknown command {cmd!r}\n{__doc__}"); return 1


if __name__ == "__main__":
    sys.exit(main())
